using System.Net.Http.Json;
using Microsoft.Data.SqlClient;
using Sistema3S.Tests.Fixtures;
using Sistema3S.Web.Services.Implementations;
using Sistema3S.Web.DTOs.Cliente;

namespace Sistema3S.Tests.Integration;
[Trait("Category","Integration")]
public class AmpliacionTests
{
    [Fact(DisplayName="PF-CLI-001 | DNI inválido no persiste; cliente válido y duplicado se verifican")]
    public async Task Cliente(){await using var q=await QaDatabase.CreateAsync();using var db=q.Open();var s=new ClienteService(db);var dto=new ClienteCrearDto{IdTipoCliente=1,IdTipoDocumento=1,NumeroDocumento="123",Nombres="Cliente",ApellidoPaterno="Prueba",ApellidoMaterno="Nueva",Correo="otro@example.test",Telefono="+51999999997"};var e=await Assert.ThrowsAsync<InvalidOperationException>(()=>s.CrearAsync(dto));Assert.Contains("8",e.Message);Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM Cliente"));dto.NumeroDocumento="00000003";var r=await s.CrearAsync(dto);Assert.True(r.IdCliente>1);Assert.Equal(2,await q.Scalar("SELECT COUNT(*) FROM ClientePersonaNatural"));await Assert.ThrowsAsync<InvalidOperationException>(()=>s.CrearAsync(dto));Assert.Equal(2,await q.Scalar("SELECT COUNT(*) FROM Cliente"));}
    [Fact(DisplayName="PI-DB-001 | Clave foránea rechaza inventario de producto inexistente")]
    public async Task Integridad(){await using var q=await QaDatabase.CreateAsync();var e=await Assert.ThrowsAsync<SqlException>(()=>q.Exec("INSERT Inventario(IdProducto,StockActual,StockMinimo) VALUES(99999,1,1)"));Assert.Equal(547,e.Number);Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM Inventario"));}
    [Fact(DisplayName="PF-CAJ-002 | Ingreso y egreso manual mantienen saldo sin permitir excederlo")]
    public async Task CajaManual(){await using var q=await QaDatabase.CreateAsync();await NegocioTests.Abrir(q,100);using var db=q.Open();var s=new CajaService(db);await s.RegistrarMovimientoManualAsync(new(){IdUsuarioRegistro=1,TipoMovimiento="Ingreso manual",MetodoPago="Efectivo",Monto=50,Descripcion="Ingreso de prueba QA"});await s.RegistrarMovimientoManualAsync(new(){IdUsuarioRegistro=1,TipoMovimiento="Egreso manual",MetodoPago="Efectivo",Monto=30,Descripcion="Egreso de prueba QA"});Assert.Equal(120,(await s.ObtenerResumenAsync(1,null)).SaldoSistema);await Assert.ThrowsAsync<InvalidOperationException>(()=>s.RegistrarMovimientoManualAsync(new(){IdUsuarioRegistro=1,TipoMovimiento="Egreso manual",MetodoPago="Efectivo",Monto=121,Descripcion="Intento excedido QA"}));Assert.Equal(2,await q.Scalar("SELECT COUNT(*) FROM MovimientoCaja"));}
    [Fact(DisplayName="PF-FLU-001 | API completa: caja, compra, venta, inventario, detalles y cierre")]
    public async Task HttpComercial(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);await ApiTests.Login(api);var caja=await ApiTests.Json(await api.Http.PostAsJsonAsync("/api/caja/abrir",new{idUsuarioApertura=99,saldoInicial=2000}));int idCaja=caja.GetProperty("idCaja").GetInt32();var compra=await ApiTests.Json(await api.Http.PostAsJsonAsync("/api/compra",NegocioTests.Compra()));int idCompra=compra.GetProperty("idCompra").GetInt32();Assert.Equal(System.Net.HttpStatusCode.OK,(await api.Http.GetAsync($"/api/compra/{idCompra}/detalle")).StatusCode);var venta=await ApiTests.Json(await api.Http.PostAsJsonAsync("/api/venta",NegocioTests.Venta()));int idVenta=venta.GetProperty("idVenta").GetInt32();Assert.Equal(354,venta.GetProperty("total").GetDecimal());Assert.Equal(System.Net.HttpStatusCode.OK,(await api.Http.GetAsync($"/api/venta/{idVenta}/detalle")).StatusCode);var stock=await ApiTests.Json(await api.Http.GetAsync("/api/inventario/1"));Assert.Equal(7,stock.GetProperty("stockActual").GetInt32());var saldo=await ApiTests.Json(await api.Http.GetAsync("/api/caja/resumen"));Assert.Equal(1854,saldo.GetProperty("saldoSistema").GetDecimal());await ApiTests.Json(await api.Http.PostAsJsonAsync("/api/caja/cerrar",new{idCaja,idUsuarioCierre=99,saldoContado=1854}));Assert.Equal(1,await q.Scalar("SELECT IdUsuarioApertura FROM Caja"));Assert.Equal(1,await q.Scalar("SELECT IdUsuarioCierre FROM Caja"));}
}
