using System.Net;
using System.Net.Http.Json;
using System.Net.Http.Headers;
using System.Text.Json;
using Sistema3S.Tests.Fixtures;

namespace Sistema3S.Tests.Integration;
[Trait("Category","Integration")]
public class ApiTests
{
    internal static async Task<JsonElement> Json(HttpResponseMessage r){var text=await r.Content.ReadAsStringAsync();Assert.True(r.IsSuccessStatusCode,$"HTTP {(int)r.StatusCode}: {text}");return JsonDocument.Parse(text).RootElement.Clone();}
    internal static async Task Login(ApiHost api,string correo="admin@example.test") {var j=await Json(await api.Http.PostAsJsonAsync("/api/auth/login",new{correo,contrasena=QaDatabase.Password}));api.Http.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",j.GetProperty("token").GetString());}
    [Fact(DisplayName="PI-WA-001 | WhatsApp genera número internacional, mensaje codificado y PDF")]
    public async Task WhatsApp(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);await Login(api);var cot=await Json(await api.Http.PostAsJsonAsync("/api/cotizacion",new{idCliente=1,origenCotizacion="Manual",detalles=new[]{new{idElementoCatalogo=1,cantidad=2,precioUnitario=118}}}));int id=cot.GetProperty("idCotizacion").GetInt32();var wa=await Json(await api.Http.GetAsync($"/api/cotizacion/{id}/whatsapp"));var url=new Uri(wa.GetProperty("url").GetString()!);Assert.Equal("wa.me",url.Host);Assert.Equal("/51999999999",url.AbsolutePath);Assert.Equal(wa.GetProperty("mensaje").GetString(),Uri.UnescapeDataString(url.Query[6..]));Assert.Contains(".pdf",wa.GetProperty("archivoPdf").GetString());Assert.True(wa.GetProperty("requiereConfirmacionRespondida").GetBoolean());}
    [Fact(DisplayName="PI-AUTH-001 | Login válido emite JWT y permite consultar usuarios")]
    public async Task LoginValido(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);await Login(api);Assert.Equal(HttpStatusCode.OK,(await api.Http.GetAsync("/api/usuario")).StatusCode);Assert.True(await q.Scalar("SELECT COUNT(*) FROM AuditoriaLog WHERE IdUsuario=1 AND Descripcion LIKE 'Auth.Login HTTP 200%'")>0);}
    [Fact(DisplayName="PI-AUTH-002 | Credenciales incorrectas no emiten token")]
    public async Task LoginInvalido(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);var r=await api.Http.PostAsJsonAsync("/api/auth/login",new{correo="admin@example.test",contrasena="incorrecta"});Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);Assert.DoesNotContain("\"token\"",await r.Content.ReadAsStringAsync());}
    [Fact(DisplayName="PS-AUTH-001 | Usuario y escritura de producto rechazan acceso anónimo")]
    public async Task Protegido(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);Assert.Equal(HttpStatusCode.Unauthorized,(await api.Http.GetAsync("/api/usuario")).StatusCode);using var form=new MultipartFormDataContent();form.Add(new StringContent("Intento QA"),"Nombre");Assert.Equal(HttpStatusCode.Unauthorized,(await api.Http.PostAsync("/api/producto",form)).StatusCode);Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM Producto"));}
    [Fact(DisplayName="PS-AUTH-002 | Listado administrativo de ventas debe exigir autenticación")]
    public async Task VentasPrivadas(){await using var q=await QaDatabase.CreateAsync();await ApiSinSesion(q,"/api/venta");}
    [Fact(DisplayName="PS-AUTH-003 | Listado administrativo de clientes debe exigir autenticación")]
    public async Task ClientesPrivados(){await using var q=await QaDatabase.CreateAsync();await ApiSinSesion(q,"/api/cliente");}
    private static async Task ApiSinSesion(QaDatabase q,string ruta){await using var api=await ApiHost.Start(q);var r=await api.Http.GetAsync(ruta);Assert.True(r.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden,$"{ruta} sin token devolvió HTTP {(int)r.StatusCode}");}
    [Fact(DisplayName="PS-ROL-001 | Personal de compras no puede anular ni consultar auditoría")]
    public async Task AnularSoloAdmin(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);await Login(api,"compras@example.test");Assert.Equal(HttpStatusCode.Forbidden,(await api.Http.PutAsJsonAsync("/api/compra/1/anular",new{motivo="Intento QA",idUsuarioRegistro=1})).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await api.Http.GetAsync("/api/auditoria")).StatusCode);}
    [Fact(DisplayName="PF-CAT-001 | Catálogo filtra búsqueda y excluye productos inactivos")]
    public async Task Catalogo(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);var r=await Json(await api.Http.GetAsync("/api/publico/productos?busqueda=PRUEBA"));Assert.Contains("Producto de prueba",r.ToString());var d=await api.Http.GetAsync("/api/publico/productos/1");Assert.Equal(HttpStatusCode.OK,d.StatusCode);await q.Exec("UPDATE ElementoCatalogo SET Estado=0 WHERE IdElementoCatalogo=1");var oculto=await Json(await api.Http.GetAsync("/api/publico/productos"));Assert.DoesNotContain("Producto de prueba",oculto.ToString());}
    [Fact(DisplayName="PF-COT-001 | Cotización manual persiste y genera PDF descargable")]
    public async Task Cotizacion(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);await Login(api);var r=await Json(await api.Http.PostAsJsonAsync("/api/cotizacion",new{idCliente=1,idUsuarioRegistro=99,origenCotizacion="Manual",detalles=new[]{new{idElementoCatalogo=1,cantidad=2,precioUnitario=118}}}));int id=r.GetProperty("idCotizacion").GetInt32();Assert.Equal(236,await q.Scalar("SELECT Total FROM Cotizacion"));Assert.Equal(1,await q.Scalar("SELECT IdUsuarioRegistro FROM Cotizacion"));var pdf=await Json(await api.Http.PostAsync($"/api/cotizacion/{id}/generar-pdf",null));Assert.Contains(".pdf",pdf.ToString());Assert.Equal(HttpStatusCode.OK,(await api.Http.GetAsync($"/api/cotizacion/{id}")).StatusCode);Assert.True(await q.Scalar("SELECT COUNT(*) FROM DetalleCotizacion")>0);}
    [Fact(DisplayName="PF-COT-002 | Cliente registra solicitud de carrito y consulta su historial")]
    public async Task Carrito(){await using var q=await QaDatabase.CreateAsync();await using var api=await ApiHost.Start(q);var usuario=await Json(await api.Http.PostAsJsonAsync("/api/cliente-web/registro",new{tipoDocumento="DNI",numeroDocumento="00000002",correo="nuevo@example.test",telefono="+51999999998",direccion="QA",contrasena=QaDatabase.Password,confirmarContrasena=QaDatabase.Password,nombres="Cliente",apellidoPaterno="Nuevo",apellidoMaterno="QA"}));var login=await Json(await api.Http.PostAsJsonAsync("/api/cliente-web/login",new{correo="nuevo@example.test",contrasena=QaDatabase.Password}));api.Http.DefaultRequestHeaders.Authorization=new("Bearer",login.GetProperty("token").GetString());var r=await Json(await api.Http.PostAsJsonAsync("/api/cliente-web/cotizaciones",new{items=new[]{new{idProducto=1,cantidad=2}}}));int id=r.GetProperty("idCotizacion").GetInt32();var detalle=await Json(await api.Http.GetAsync($"/api/cliente-web/cotizaciones/{id}"));Assert.Equal(2,detalle.GetProperty("detalles")[0].GetProperty("cantidad").GetInt32());Assert.Contains("Producto de prueba",detalle.ToString());Assert.Equal(HttpStatusCode.Forbidden,(await api.Http.GetAsync("/api/auditoria")).StatusCode);}
}
