using Sistema3S.Tests.Fixtures;
using Sistema3S.Web.DTOs.Compra;
using Sistema3S.Web.DTOs.Venta;
using Sistema3S.Web.DTOs.Caja;
using Sistema3S.Web.DTOs.Producto;
using Sistema3S.Web.Services.Implementations;
using Sistema3S.Web.Services.Seguridad;

namespace Sistema3S.Tests.Integration;
[Trait("Category","Integration")]
public class NegocioTests
{
    internal static CompraCrearDto Compra(decimal pago=500,int cantidad=10) => new(){IdProveedor=1,IdUsuarioRegistro=1,TipoComprobanteProveedor="Factura",SerieComprobante="QA01",NumeroComprobante=Guid.NewGuid().ToString("N")[..8],FechaEmisionComprobante=DateTime.Today,TipoPago=pago==cantidad*100?"Total":"Parcial",MetodoPago="Efectivo",MontoPagado=pago,Detalles=[new(){IdProducto=1,Cantidad=cantidad,PrecioCompra=100}]};
    internal static VentaCrearDto Venta(int cantidad=3,string tipo="Boleta") => new(){IdCliente=1,IdUsuarioRegistro=1,TipoComprobante=tipo,TipoPago="Total",MetodoPago="Efectivo",MontoPagado=cantidad*118,Detalles=[new(){IdElementoCatalogo=1,Cantidad=cantidad,PrecioUnitario=118}]};
    internal static async Task Abrir(QaDatabase q,decimal saldo=2000){using var db=q.Open();await new CajaService(db).AbrirCajaAsync(new(){IdUsuarioApertura=1,SaldoInicial=saldo});}

    [Fact(DisplayName="PF-COM-001 | Compra parcial aumenta stock y descuenta sólo el pago")]
    public async Task CompraParcial(){await using var q=await QaDatabase.CreateAsync();await Abrir(q,600);using var db=q.Open();var r=await new CompraService(db).RegistrarCompraCompletaAsync(Compra());Assert.Equal(1000,r.Total);Assert.Equal(500,r.TotalPagado);Assert.Equal(500,r.SaldoPendiente);Assert.Equal(10,await q.Scalar("SELECT StockActual FROM Inventario WHERE IdProducto=1"));Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM DetalleCompra"));Assert.Equal(100,(await new CajaService(db).ObtenerResumenAsync(1,null)).SaldoSistema);}
    [Fact(DisplayName="PF-COM-002 | Pago mayor al saldo rechaza compra completa sin persistencia")]
    public async Task CompraSinSaldo(){await using var q=await QaDatabase.CreateAsync();await Abrir(q,200);using var db=q.Open();var e=await Assert.ThrowsAsync<InvalidOperationException>(()=>new CompraService(db).RegistrarCompraCompletaAsync(Compra()));Assert.Contains("saldo",e.Message,StringComparison.OrdinalIgnoreCase);Assert.Equal(0,await q.Scalar("SELECT COUNT(*) FROM Compra"));Assert.Equal(0,await q.Scalar("SELECT StockActual FROM Inventario WHERE IdProducto=1"));Assert.Equal(0,await q.Scalar("SELECT COUNT(*) FROM MovimientoCaja"));}
    [Fact(DisplayName="PF-COM-003 | Anulación revierte stock y caja una sola vez")]
    public async Task Anulacion(){await using var q=await QaDatabase.CreateAsync();await Abrir(q);using var db=q.Open();ContextoAuditoria.Actual.Value=new(){IdUsuario=1,Accion="QA.Anular",Origen="Administración"};try{var s=new CompraService(db);var r=await s.RegistrarCompraCompletaAsync(Compra());Assert.True(await s.AnularAsync(r.IdCompra,new(){IdUsuarioRegistro=1,Motivo="Anulación QA"}));Assert.Equal(0,await q.Scalar("SELECT StockActual FROM Inventario WHERE IdProducto=1"));Assert.Equal(2000,(await new CajaService(db).ObtenerResumenAsync(1,null)).SaldoSistema);await Assert.ThrowsAsync<InvalidOperationException>(()=>s.AnularAsync(r.IdCompra,new(){IdUsuarioRegistro=1,Motivo="Duplicada QA"}));Assert.Equal(2000,(await new CajaService(db).ObtenerResumenAsync(1,null)).SaldoSistema);}finally{ContextoAuditoria.Actual.Value=null;}}
    [Fact(DisplayName="PF-VEN-001 | Venta persiste detalle, IGV, salida de stock y cobro en caja")]
    public async Task VentaCompleta(){await using var q=await QaDatabase.CreateAsync();await Abrir(q);using var db=q.Open();await new CompraService(db).RegistrarCompraCompletaAsync(Compra());var r=await new VentaService(db).RegistrarVentaCompletaAsync(Venta());Assert.Equal(354,r.Total);Assert.Equal(300,r.Subtotal);Assert.Equal(54,r.Igv);Assert.Equal(7,await q.Scalar("SELECT StockActual FROM Inventario WHERE IdProducto=1"));Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM DetalleVenta"));Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM PagoVenta"));Assert.Equal(1854,(await new CajaService(db).ObtenerResumenAsync(1,null)).SaldoSistema);}
    [Fact(DisplayName="PF-VEN-002 | Factura a persona con DNI se rechaza sin venta ni salida")]
    public async Task FacturaDni(){await using var q=await QaDatabase.CreateAsync();await Abrir(q);using var db=q.Open();await new CompraService(db).RegistrarCompraCompletaAsync(Compra());var e=await Assert.ThrowsAsync<InvalidOperationException>(()=>new VentaService(db).RegistrarVentaCompletaAsync(Venta(1,"Factura")));Assert.Contains("RUC",e.Message,StringComparison.OrdinalIgnoreCase);Assert.Equal(0,await q.Scalar("SELECT COUNT(*) FROM Venta"));Assert.Equal(10,await q.Scalar("SELECT StockActual FROM Inventario WHERE IdProducto=1"));}
    [Fact(DisplayName="PF-VEN-003 | Stock insuficiente revierte toda la venta")]
    public async Task StockInsuficiente(){await using var q=await QaDatabase.CreateAsync();await Abrir(q);using var db=q.Open();var e=await Assert.ThrowsAsync<InvalidOperationException>(()=>new VentaService(db).RegistrarVentaCompletaAsync(Venta()));Assert.Contains("stock",e.Message,StringComparison.OrdinalIgnoreCase);Assert.Equal(0,await q.Scalar("SELECT COUNT(*) FROM Venta"));Assert.Equal(0,await q.Scalar("SELECT COUNT(*) FROM PagoVenta"));Assert.Equal(2000,(await new CajaService(db).ObtenerResumenAsync(1,null)).SaldoSistema);}
    [Fact(DisplayName="PF-PRO-001 | Nuevo producto inicia sin stock ni mínimo y código duplicado se rechaza")]
    public async Task Producto(){await using var q=await QaDatabase.CreateAsync();using var db=q.Open();var s=new ProductoService(db);var d=new ProductoCrearDto{Nombre="Producto QA nuevo",CodigoProducto="QA-NUEVO",Descripcion="Sintético",PrecioReferencial=118,IdCategoria=1,IdUnidadMedida=1,ImagenUrl="/qa.png"};var r=await s.CrearAsync(d);Assert.True(r.IdProducto>1);Assert.Equal(0,r.StockActual);Assert.Equal(0,r.StockMinimo);await Assert.ThrowsAsync<InvalidOperationException>(()=>s.CrearAsync(d));Assert.Equal(2,await q.Scalar("SELECT COUNT(*) FROM Producto"));}
    [Fact(DisplayName="PF-STO-001 | Entrada manual y mínimo persisten con trazabilidad")]
    public async Task StockManual(){await using var q=await QaDatabase.CreateAsync();using var db=q.Open();ContextoAuditoria.Actual.Value=new(){IdUsuario=1,Accion="QA.Stock",Origen="Administración"};try{var s=new InventarioService(db);var r=await s.RegistrarMovimientoManualAsync(new(){IdProducto=1,IdUsuarioRegistro=1,TipoMovimiento="Entrada",Cantidad=20,Motivo="Ingreso QA"});Assert.Equal(20,r.StockActual);var m=await s.ActualizarStockMinimoAsync(1,new(){StockMinimo=8});Assert.Equal(8,m.StockMinimo);Assert.True(await q.Scalar("SELECT COUNT(*) FROM AuditoriaLog WHERE IdUsuario=1")>0);Assert.Equal(1,await q.Scalar("SELECT COUNT(*) FROM MovimientoStock"));}finally{ContextoAuditoria.Actual.Value=null;}}
    [Fact(DisplayName="PF-CAJ-001 | Caja no admite segunda apertura y cierra con saldo esperado")]
    public async Task Caja(){await using var q=await QaDatabase.CreateAsync();await Abrir(q);using var db=q.Open();var s=new CajaService(db);await Assert.ThrowsAsync<InvalidOperationException>(()=>s.AbrirCajaAsync(new(){IdUsuarioApertura=1,SaldoInicial=10}));var c=await s.ObtenerCajaActivaAsync(1);Assert.NotNull(c);await s.CerrarCajaAsync(new(){IdCaja=c.IdCaja,IdUsuarioCierre=1,SaldoContado=2000});Assert.Null(await s.ObtenerCajaActivaAsync(1));}
}
